const analytics=(tac:number,netYield:number,productionReturn:number,score:number,riskLabel:string,confidence:number,verdict:string)=>({
 tac,netYield,productionReturnMetric:"IRR",productionReturn,riskAdjustedScore:score,
 riskLabel,dataConfidence:confidence,finalVerdict:verdict,methodologyVersion:"1.0"
});

const seeds=[
 {id:"demo-layan-01",project:"Layan Ridge Residences",unit:"Villa L-07",headline:"Privacy with a disciplined entry price.",summary:"A low-density villa scenario where location quality is strong, but the investment case still depends on controlled operating costs and a realistic exit.",imageUrl:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85",price:18_900_000,priceStatus:"DEVELOPER_MODEL",noiStatus:"PP_ESTIMATE",analytics:analytics(20_150_000,.064,.108,81.4,"MODERATE",86,"BUY"),whyBuy:["Low-density product in an established premium micro-location.","Entry price leaves room for furnishing and transaction costs.","Exit assumptions do not rely on aggressive double-digit growth."],whyNotBuy:["Villa operations require active cost control.","Resale liquidity is narrower than for a compact condominium.","Rental demand is seasonal and management quality is material."],sources:[{status:"DEVELOPER_MODEL",label:"Price and payment schedule"},{status:"MARKET_DATA",label:"Comparable villa asking prices"},{status:"PP_ESTIMATE",label:"Operating cost model"}],scenarios:[{name:"Base",text:"5-year hold, 4.0% annual value growth, 5.0% selling cost."},{name:"Bear",text:"Flat exit value and 12% lower annual NOI."},{name:"Bull",text:"6.0% annual growth with stable occupancy."}]},
 {id:"demo-bangtao-02",project:"Bang Tao Courtyard",unit:"Residence C-12",headline:"The strongest income profile in the shortlist.",summary:"A one-bedroom residence close to everyday infrastructure. The model favours rental economics, while supply pressure keeps the verdict below an unconditional recommendation.",imageUrl:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85",price:9_750_000,priceStatus:"VERIFIED_DOCUMENT",noiStatus:"MARKET_DATA",analytics:analytics(10_390_000,.079,.126,76.8,"ELEVATED",91,"CONSIDER"),whyBuy:["Walkable access to established Bang Tao infrastructure.","Compact format supports a broad rental audience.","Net yield remains resilient in the base model."],whyNotBuy:["Significant competing condominium supply is planned nearby.","The return is sensitive to daily-rate compression.","View and floor differences can materially affect resale."],sources:[{status:"VERIFIED_DOCUMENT",label:"Developer price list"},{status:"MARKET_DATA",label:"Comparable rental evidence"},{status:"VERIFIED_DOCUMENT",label:"Unit specification"}],scenarios:[{name:"Base",text:"5-year hold, 3.5% annual value growth, 5.0% selling cost."},{name:"Bear",text:"15% lower NOI and no capital growth."},{name:"Bull",text:"5.5% annual growth and stronger high-season rates."}]},
 {id:"demo-naiyang-03",project:"Nai Yang Garden Suites",unit:"Suite B-34",headline:"Lower entry cost, higher location concentration.",summary:"An accessible resort-apartment scenario near the airport and national park. The numbers are attractive, but demand concentration and developer execution require a larger margin of safety.",imageUrl:"https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85",price:6_450_000,priceStatus:"DEVELOPER_MODEL",noiStatus:"DEVELOPER_CLAIM",analytics:analytics(6_920_000,.073,.097,68.9,"HIGH",72,"WATCH"),whyBuy:["Lower absolute ticket than the other preview scenarios.","Airport and national-park demand provide clear positioning.","Compact format limits furnishing and maintenance exposure."],whyNotBuy:["Confidence is below the final-verdict threshold.","Income evidence is still a developer claim, not operating history.","The location has a narrower year-round tenant base."],sources:[{status:"DEVELOPER_MODEL",label:"Price and payment schedule"},{status:"DEVELOPER_CLAIM",label:"Rental projection"},{status:"TO_VERIFY",label:"Final common-area fee"}],scenarios:[{name:"Base",text:"5-year hold, 3.0% annual value growth, 5.0% selling cost."},{name:"Bear",text:"20% lower NOI and flat exit value."},{name:"Bull",text:"5.0% annual growth with improved occupancy."}]}
];

export const demoCatalog=seeds.map(({price,priceStatus,noiStatus,whyBuy,whyNotBuy,sources,scenarios,...item})=>item);

export function demoProperty(id:string){
 const item=seeds.find(x=>x.id===id); if(!item)return undefined;
 return {publication:{id:`publication-${item.id}`,property_id:item.id,calculation_run_id:`preview-${item.id}`,published_at:"2026-09-18T00:00:00.000Z"},lifecycle:{status:"DESIGN_PREVIEW"},snapshot:{property:{id:item.id,project:item.project,unit:item.unit,purchasePrice:{value:item.price,status:item.priceStatus},annualNoi:{value:item.analytics.tac*item.analytics.netYield,status:item.noiStatus}},analytics:{...item.analytics,calculationRunId:`preview-${item.id}`,engineVersion:"preview-1.0",inputSnapshotHash:"illustrative-preview-data",verdictStatus:item.analytics.dataConfidence>=75?"FINAL":"PROVISIONAL"},narrative:{headline:item.headline,summary:item.summary,whyBuy:item.whyBuy,whyNotBuy:item.whyNotBuy},sourceDisclosures:item.sources,scenarioDisclosures:item.scenarios,frozenAt:"2026-09-18T00:00:00.000Z",imageUrl:item.imageUrl}};
}
