import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {api} from "./lib/api";
import {submitEvidenceMutation} from "./lib/evidence-mutation";
import "./styles.css";
type View="dashboard"|"properties"|"verification"|"property";
const STATUSES=["VERIFIED_DOCUMENT","ACTUAL","MARKET_DATA","DEVELOPER_MODEL","PP_ESTIMATE","DEVELOPER_CLAIM","ASSUMPTION","TO_VERIFY"];
const EVIDENCE_GROUPS=[
 {label:"Purchase / Entry Value · 15%",fields:[{value:"purchasePrice",label:"Purchase price",unit:"THB"},{value:"entryMarketValue",label:"Entry market value",unit:"THB"}]},
 {label:"Ownership / Legal · 15%",fields:[{value:"ownershipType",label:"Ownership type",unit:""},{value:"titleStatus",label:"Title status",unit:""},{value:"legalStatus",label:"Legal status",unit:""}]},
 {label:"Acquisition Costs · 10%",fields:[{value:"acquisitionCosts",label:"Acquisition costs",unit:"THB"},{value:"initialCapex",label:"Initial CAPEX",unit:"THB"}]},
 {label:"Rental Revenue / NOI · 20%",fields:[{value:"annualNoi",label:"Annual NOI",unit:"THB/year"},{value:"rentalRevenue",label:"Rental revenue",unit:"THB/year"}]},
 {label:"Operating Expenses · 10%",fields:[{value:"operatingExpenses",label:"Operating expenses",unit:"THB/year"}]},
 {label:"Payment Schedule / Timing · 10%",fields:[{value:"datedCashFlows",label:"Dated cash flows",unit:"JSON"},{value:"paymentSchedule",label:"Payment schedule",unit:"JSON"}]},
 {label:"Exit Growth / Market Value · 10%",fields:[{value:"exitGrowthRate",label:"Exit growth rate",unit:"decimal"},{value:"exitMarketValue",label:"Exit market value",unit:"THB"}]},
 {label:"Exit Costs · 5%",fields:[{value:"sellingCostRate",label:"Selling cost rate",unit:"decimal"},{value:"exitCosts",label:"Exit costs",unit:"THB"}]},
 {label:"Developer / Delivery · 5%",fields:[{value:"developerStatus",label:"Developer status",unit:""},{value:"developerDelivery",label:"Developer delivery",unit:""}]}
] as const;
const EVIDENCE_FIELDS=EVIDENCE_GROUPS.flatMap(g=>g.fields);
function Badge({children,kind=""}:{children:React.ReactNode,kind?:string}){return <span className={`badge ${kind}`}>{children}</span>}
function Shell({view,setView,children}:{view:View,setView:(v:View)=>void,children:React.ReactNode}){return <div className="app"><aside><div className="brand">PP <span className="gold">PrivatePhuket</span></div><div className="muted" style={{marginTop:6,color:"#87908c"}}>Analyst Operations · v0.5</div><nav>{[["dashboard","Dashboard"],["properties","Properties"],["verification","Verification Queue"]].map(([v,l])=><button key={v} className={`nav ${view===v?"active":""}`} onClick={()=>setView(v as View)}>{l}</button>)}</nav></aside><main>{children}</main></div>}
function Dashboard({go}:{go:(v:View)=>void}){const [ps,setPs]=useState<any[]>([]),[vi,setVi]=useState<any[]>([]);useEffect(()=>{api.properties().then(setPs).catch(()=>{});api.verification().then(setVi).catch(()=>{})},[]);return <><div className="eyebrow">Operational control</div><h1>Dashboard</h1><div className="grid"><div className="card"><div className="muted">Properties</div><div className="metric">{ps.length}</div></div><div className="card"><div className="muted">Open verification</div><div className="metric">{vi.length}</div></div><div className="card"><div className="muted">Open queue blockers</div><div className="metric">{vi.filter(x=>x.severity==="BLOCKER").length}</div></div><div className="card"><div className="muted">Operating model</div><div style={{marginTop:12,fontWeight:700}}>EVIDENCE → REVIEW → PUBLISH</div></div></div><div className="toolbar"><button className="primary" onClick={()=>go("properties")}>Work with properties</button><button className="secondary" onClick={()=>go("verification")}>Resolve blockers</button></div></>}
function Properties({open}:{open:(id:string)=>void}){const [data,setData]=useState<any[]>([]);useEffect(()=>{api.properties().then(setData)},[]);return <><div className="eyebrow">Portfolio</div><h1>Properties</h1><table><thead><tr><th>Project</th><th>Unit</th><th>Workflow</th><th>Confidence</th><th></th></tr></thead><tbody>{data.map(p=><tr key={p.id}><td><b>{p.project}</b></td><td>{p.unit??"—"}</td><td><Badge>{p.workflow}</Badge></td><td>{p.dataConfidence?`${p.dataConfidence.toFixed(0)}/100`:"—"}</td><td><button className="secondary" onClick={()=>open(p.id)}>Open</button></td></tr>)}</tbody></table></>}
const VERIFICATION_GUIDANCE:Record<string,string>={
 MISSING_PURCHASE_PRICE:"Add the official price list or signed booking document.",
 MISSING_OWNERSHIP:"Add title or SPA evidence confirming the ownership structure.",
 MISSING_PAYMENT_SCHEDULE:"Upload the official SPA or payment schedule with all tranches.",
 NON_EXACT_PAYMENT_DATES:"Replace month-only dates with exact contract dates.",
 INVALID_PAYMENT_DATE:"Correct every cash-flow date to a valid YYYY-MM-DD calendar date.",
 CRITICAL_TO_VERIFY:"Add source-backed evidence for the critical input.",
 EVIDENCE_TO_VERIFY:"Supersede the unverified value with source-backed evidence."
};
function Verification({open}:{open:(id:string)=>void}){
 const [items,setItems]=useState<any[]>([]),[properties,setProperties]=useState<any[]>([]);
 const load=()=>Promise.all([api.verification(),api.properties()]).then(([verification,portfolio])=>{setItems(verification);setProperties(portfolio);});
 useEffect(()=>{load()},[]);
 const resolve=async(x:any)=>{const c=prompt("Resolution comment");if(!c)return;await api.resolveVerification(x.id,c);load();};
 const propertyName=(id:string)=>{const p=properties.find(x=>x.id===id);return p?[p.project,p.unit].filter(Boolean).join(" / "):id;};
 return <><div className="eyebrow">Evidence control</div><h1>Verification Queue</h1>
 {items.length===0?<div className="card"><b>No open verification items.</b><div className="muted" style={{marginTop:8}}>Sync verification for each property after adding evidence. An empty queue does not mean the property is ready to calculate or publish.</div></div>:
 <table><thead><tr><th>Severity</th><th>Property</th><th>Field / code</th><th>Issue</th><th>Required action</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}>
  <td><Badge kind={x.severity==="BLOCKER"?"blocker":"warn"}>{x.severity}</Badge></td>
  <td><b>{propertyName(x.property_id)}</b></td>
  <td>{x.field??"—"}<div className="muted">{x.code}</div></td>
  <td>{x.message}</td>
  <td>{VERIFICATION_GUIDANCE[x.code]??"Review the evidence and document the resolution."}</td>
  <td>{x.severity==="BLOCKER"?<button className="primary" onClick={()=>open(x.property_id)}>Open property</button>:<button className="secondary" onClick={()=>resolve(x)}>Resolve</button>}</td>
 </tr>)}</tbody></table>}</>;
}
function PropertyView({id}:{id:string}){
 const [p,setP]=useState<any>(),[validation,setValidation]=useState<{readyToCalculate:boolean,issues:{severity:string,code:string,field?:string,message:string}[]}|null>(null),[sources,setSources]=useState<any[]>([]),[evidence,setEvidence]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[preview,setPreview]=useState<any>(),[notice,setNotice]=useState(""),[savingEvidence,setSavingEvidence]=useState(false);
 const [sourceForm,setSourceForm]=useState({documentType:"PRICE_LIST",title:"",issuer:"",sourceDate:"",uri:"",status:"VERIFIED_DOCUMENT"});
 const [evForm,setEvForm]=useState({field:"purchasePrice",value:"",unit:"THB",status:"VERIFIED_DOCUMENT",sourceId:"",isCritical:true,analystComment:""});
 const load=async()=>{setP(await api.property(id));setSources(await api.sources(id));setEvidence(await api.evidence(id));setRuns(await api.calculations(id));setValidation(await api.validate(id).catch(()=>null));};
 useEffect(()=>{load()},[id]);if(!p)return <div>Loading…</div>;
 const addSource=async()=>{setNotice("");const created=await api.createSource(id,sourceForm);setSourceForm({...sourceForm,title:"",issuer:"",sourceDate:"",uri:""});await load();setEvForm(current=>({...current,sourceId:created.id}));setNotice(`Source saved and selected: ${created.title??created.document_type??created.id}`);};
 const chooseEvidenceField=(field:string)=>{const def=EVIDENCE_FIELDS.find(x=>x.value===field);setEvForm(current=>({...current,field,unit:def?.unit??"",value:""}));};
 const addEvidence=async()=>{setNotice("");if(savingEvidence)return;if(evForm.status==="VERIFIED_DOCUMENT"&&!evForm.sourceId){setNotice("VERIFIED_DOCUMENT requires a linked source.");return;}if(evForm.value.trim()===""){setNotice("Evidence value is required.");return;}let value:any=evForm.value;if(evForm.unit==="JSON"){try{value=JSON.parse(evForm.value)}catch{setNotice("JSON evidence must be valid JSON.");return;}}else if(!Number.isNaN(Number(value))&&value!=="")value=Number(value);setSavingEvidence(true);const result=await submitEvidenceMutation(()=>api.createEvidence(id,{...evForm,value,sourceId:evForm.sourceId||undefined}));setSavingEvidence(false);setNotice(result.notice);if(!result.ok)return;setEvForm({...evForm,value:"",analystComment:""});await load();};
 const syncVerification=async()=>{try{const result=await api.syncVerification(id);await load();setNotice(`Verification synced: ${result.count} current issue${result.count===1?"":"s"}. Calculation readiness refreshed below.`)}catch(error){setNotice(`Verification sync failed: ${error instanceof Error?error.message:String(error)}`)}};
 const calc=async()=>{await api.calculate(id);await load();};const review=async(run:any,status:"APPROVED"|"REJECTED")=>{await api.reviewRun(run.calculationRunId,status);await load();};const publish=async(run:any)=>{await api.publish(id,run.calculationRunId);setPreview(await api.publicView(id));};
 const sourceName=(sourceId:string)=>{const s=sources.find(x=>x.id===sourceId);return s?(s.title??s.document_type??s.id):sourceId;};
 return <><div className="eyebrow">Property workspace</div><h1>{p.project} {p.unit&&`/ ${p.unit}`}</h1><div className="grid"><div className="card"><div className="muted">Price</div><div className="value">{p.purchasePrice?.value?.toLocaleString?.()??"—"} THB</div><Badge>{p.purchasePrice?.status??"NO DATA"}</Badge></div><div className="card"><div className="muted">Confidence</div><div className="value">{(p.dataConfidence??0).toFixed(0)}/100</div></div><div className="card"><div className="muted">Critical TO VERIFY</div><div className="value">{p.criticalToVerify?"YES":"NO"}</div></div><div className="card"><div className="muted">Runs</div><div className="value">{runs.length}</div></div></div><div className="toolbar"><button className="secondary" onClick={syncVerification}>Sync verification</button><button className="primary" onClick={calc}>Run calculation</button></div>{notice&&<div className="card" role="status"><b>{notice}</b></div>}
 <div className="card" role="region" aria-label="Calculation readiness"><h2>Calculation readiness</h2>{validation?<><Badge kind={validation.readyToCalculate?"ok":"blocker"}>{validation.readyToCalculate?"No calculation blockers":"Calculation blocked"}</Badge>{validation.issues.length>0&&<ul>{validation.issues.map((issue,index)=><li key={index}><b>{issue.severity}</b> · {issue.field??issue.code}: {issue.message}</li>)}</ul>}</>:<div className="muted">Could not load calculation validation.</div>}<p className="muted">This check covers calculation inputs only. Publication also requires source closure, a FINAL run, analyst review and approval.</p></div>
 <div className="split"><div className="stack"><div className="card"><h2>Add Source</h2><div className="formgrid"><input placeholder="Title" value={sourceForm.title} onChange={e=>setSourceForm({...sourceForm,title:e.target.value})}/><input placeholder="Issuer" value={sourceForm.issuer} onChange={e=>setSourceForm({...sourceForm,issuer:e.target.value})}/><input placeholder="Document type" value={sourceForm.documentType} onChange={e=>setSourceForm({...sourceForm,documentType:e.target.value})}/><input type="date" aria-label="Source date" value={sourceForm.sourceDate} onChange={e=>setSourceForm({...sourceForm,sourceDate:e.target.value})}/><input placeholder="Stable URI or file ID" value={sourceForm.uri} onChange={e=>setSourceForm({...sourceForm,uri:e.target.value})}/><select value={sourceForm.status} onChange={e=>setSourceForm({...sourceForm,status:e.target.value})}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div><div className="muted" style={{marginTop:8}}>Verified documents require title, issuer, document date, and a stable link or file identifier.</div><button className="primary" onClick={addSource}>Save source</button>{sources.length>0&&<div style={{marginTop:16}}><div className="muted">Linked sources</div>{sources.map(s=><div key={s.id} style={{marginTop:8}}><b>{s.title??s.document_type}</b> · {s.issuer??"Unknown issuer"} · <Badge>{s.status}</Badge></div>)}</div>}</div>
 <div className="card"><h2>Add Evidence</h2><div className="formgrid"><select value={evForm.field} onChange={e=>chooseEvidenceField(e.target.value)}>{EVIDENCE_GROUPS.map(g=><optgroup key={g.label} label={g.label}>{g.fields.map(f=><option key={f.value} value={f.value}>{f.label} · {f.value}</option>)}</optgroup>)}</select><input placeholder="Value" value={evForm.value} onChange={e=>setEvForm({...evForm,value:e.target.value})}/><input placeholder="Unit" value={evForm.unit} onChange={e=>setEvForm({...evForm,unit:e.target.value})}/><select value={evForm.status} onChange={e=>setEvForm({...evForm,status:e.target.value})}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><select value={evForm.sourceId} onChange={e=>setEvForm({...evForm,sourceId:e.target.value})}><option value="">No source</option>{sources.map(s=><option key={s.id} value={s.id}>{s.title??s.document_type}</option>)}</select><input placeholder="Analyst comment" value={evForm.analystComment} onChange={e=>setEvForm({...evForm,analystComment:e.target.value})}/></div><label><input type="checkbox" checked={evForm.isCritical} onChange={e=>setEvForm({...evForm,isCritical:e.target.checked})}/> Critical input</label><div className="muted" style={{marginTop:8}}>Field catalog is governed by the production Data Confidence categories. JSON fields require valid JSON.</div><div><button className="primary" disabled={savingEvidence} onClick={addEvidence}>{savingEvidence?"Saving…":"Save evidence"}</button></div></div>
 <div className="card"><h2>Evidence history</h2><table><thead><tr><th>Field</th><th>Value</th><th>Status</th><th>Source</th></tr></thead><tbody>{evidence.slice().reverse().slice(0,12).map(e=><tr key={e.id}><td>{e.field}</td><td>{typeof e.value==="object"?JSON.stringify(e.value):String(e.value)}</td><td><Badge>{e.status}</Badge></td><td>{e.source_id?sourceName(e.source_id):"—"}</td></tr>)}</tbody></table></div></div>
 <div className="stack"><div className="card"><h2>Calculation History</h2>{runs.length===0?<div className="muted">No runs yet.</div>:runs.map((r:any)=><div className="run" key={r.calculationRunId}><b>{r.productionReturnMetric??"CALCULATION"}</b> · {r.productionReturn==null?"—":`${(r.productionReturn*100).toFixed(2)}%`}<br/><Badge kind={r.verdictStatus==="FINAL"?"ok":"warn"}>{r.verdictStatus}</Badge> <Badge>{r.reviewStatus??"PENDING"}</Badge><div className="muted">{r.provisionalVerdict??r.finalVerdict??"No verdict"} · engine {r.engineVersion}</div><div className="toolbar mini"><button className="secondary" onClick={()=>review(r,"APPROVED")}>Approve</button><button className="secondary" onClick={()=>review(r,"REJECTED")}>Reject</button><button className="primary" disabled={r.verdictStatus!=="FINAL"||r.reviewStatus!=="APPROVED"} onClick={()=>publish(r)}>Publish</button></div></div>)}</div><div className="card"><h2>Public Preview</h2>{!preview?<div className="muted">Publish an approved FINAL run to preview the public read-model.</div>:<><div className="value">{preview.analytics.finalVerdict}</div><div className="muted">Score {preview.analytics.riskAdjustedScore?.toFixed?.(1)} · Confidence controlled by backend</div></>}</div></div></div></>;
}
function App(){const [view,setView]=useState<View>("dashboard"),[pid,setPid]=useState("");const open=(id:string)=>{setPid(id);setView("property")};return <Shell view={view} setView={setView}>{view==="dashboard"?<Dashboard go={setView}/>:view==="properties"?<Properties open={open}/>:view==="verification"?<Verification open={open}/>:<PropertyView id={pid}/>}</Shell>}
createRoot(document.getElementById("root")!).render(<App/>);
