import React from "react";
import {language,pageHref} from "./lib/i18n";
import "./landing.css";
const ru=language==="ru";
const t=(a:string,b:string)=>ru?a:b;
export type Journey="rent"|"living"|"villas";
const journeys={
 rent:{title:t("Для сдачи в аренду","For rental income"),lead:t("Доход начинается не с обещанного процента.","Returns start with more than a promised percentage."),intro:t("Выбирайте объект по чистому доходу после расходов, условиям управления и устойчивости спроса. Красивый прогноз ещё не означает работающую инвестицию.","Choose by net income after costs, management terms and rental demand. An attractive forecast is not an operating investment."),points:[t("Чистый доход, а не выручка","Net income, not revenue"),t("Условия управления и удержания","Management terms and deductions"),t("Срок запуска и сценарий выхода","Launch timing and exit scenario")],notes:[t("Учитываем загрузку, сезонность, коммунальные платежи, обслуживание и вознаграждение управляющей компании.","Consider occupancy, seasonality, utilities, maintenance and management fees."),t("Проверяем распределение прибыли, ограничения личного проживания и перечень расходов собственника.","Check profit sharing, personal-use restrictions and owner expenses."),t("Сопоставляем график платежей, риски задержки и расходы при будущей продаже.","Compare payment schedules, delay risks and future selling costs.")]},
 living:{title:t("Для жизни","For living"),lead:t("Не просто квартира. Ваш привычный ритм жизни.","More than a home. Your way of life."),intro:t("Сначала — повседневные маршруты и требования семьи. Затем — район, проект и планировка. Доходность не должна подменять комфорт собственного дома.","Start with daily routines and family needs. Then choose the area, project and layout. Investment returns should not replace comfort."),points:[t("Окружение и маршруты","Neighbourhood and daily routes"),t("Планировка и приватность","Layout and privacy"),t("Готовность и содержание","Readiness and running costs")],notes:[t("Проверяем дорогу до школы, пляжа, магазинов и медицинских учреждений — не только расстояние на карте.","Assess routes to schools, beaches, shops and healthcare, not just distances on a map."),t("Смотрим на свет, шум, хранение, вид из окон и удобство пространства для вашей семьи.","Consider light, noise, storage, views and how the space works for your family."),t("Разбираем срок передачи, комплектацию, правила комплекса и регулярные расходы.","Review handover timing, fit-out, community rules and ongoing expenses.")]},
 villas:{title:t("Виллы","Villas"),lead:t("Больше пространства. Больше внимания к деталям.","More space. More attention to detail."),intro:t("Вилла может быть домом для семьи или арендным активом. В обоих случаях важны не только архитектура и бассейн, но и земля, доступ, приватность и стоимость содержания.","A villa can be a family home or a rental asset. Beyond architecture and a pool, consider land, access, privacy and maintenance."),points:[t("Участок и окружение","Land and surroundings"),t("Правовая структура сделки","Transaction structure"),t("Эксплуатация без сюрпризов","Predictable operation")],notes:[t("Изучаем границы участка, подъезд, соседнюю застройку, рельеф и фактическую приватность.","Review boundaries, access, neighbouring development, terrain and actual privacy."),t("Форму владения землёй и строением рассматриваем отдельно; документы проверяются для конкретной сделки.","Review land and building ownership separately; documents require transaction-specific checks."),t("Учитываем обслуживание бассейна, сада, инженерных систем, охрану и управление арендой.","Account for pool, garden, engineering systems, security and rental management.")]}
};
export function SiteNavigation(){return <><a href={pageHref()}>{t("Главная","Home")}</a><a href={pageHref("page=rent")}>{journeys.rent.title}</a><a href={pageHref("page=living")}>{journeys.living.title}</a><a href={pageHref("page=villas")}>{journeys.villas.title}</a><a href={pageHref("page=catalog")}>{t("Объекты","Properties")}</a></>}
function Actions(){return <div className="landingActions"><a className="landingPrimary" href={pageHref("page=catalog")}>{t("Смотреть объекты","Explore properties")} <span>↗</span></a><a className="landingSecondary" href={pageHref("calculator=1")}>{t("Проверить инвестиционный сценарий","Test an investment scenario")} →</a></div>}
function JourneyCards(){return <div className="journeyGrid">{(Object.keys(journeys) as Journey[]).map((key,i)=><a className="journeyCard" href={pageHref(`page=${key}`)} key={key}><span className="journeyNumber">0{i+1}</span><h3>{journeys[key].title}</h3><p>{journeys[key].intro}</p><span className="journeyLink">{t("Выбрать направление","Explore this direction")} ↗</span></a>)}</div>}
export function Landing({journey}:{journey?:Journey}){
 const data=journey?journeys[journey]:null;
 React.useEffect(()=>{document.title=`${data?.title??t("Недвижимость с ясной логикой выбора","Property with a clear decision framework")} — PrivatePhuket`},[journey]);
 return <main className="landingMain"><section className={`landingHero ${data?"journeyHero":""}`}><div className="landingHeroCopy"><div className="eyebrow">PRIVATEPHUKET · {data?.title??t("НЕДВИЖИМОСТЬ ПХУКЕТА","PHUKET REAL ESTATE")}</div><h1>{data?.lead??t("Ваш Пхукет.\nВаш сценарий.","Your Phuket.\nYour next chapter.")}</h1><p>{data?.intro??t("Для жизни, арендного дохода или собственного пространства. Помогаем выбирать недвижимость с пониманием цены, условий и рисков — без обещаний, которые нельзя проверить.","For living, rental income or a place of your own. Choose with a clear view of price, terms and risks, without promises that cannot be verified.")}</p><Actions/></div>{journey!=="villas"?<figure className="landingVisual"><img src={journey==="living"?"/assets/b3-301/interior.webp":"/assets/b3-301/architecture.webp"} alt={t("Визуализация проекта Layan Verde","Layan Verde project visualisation")}/><figcaption>LAYAN VERDE · {t("ВИЗУАЛИЗАЦИЯ ПРОЕКТА","PROJECT VISUALISATION")}</figcaption></figure>:<aside className="villaEditorial"><span>PRIVATE SPACE</span><p>{t("Дом.\nЗемля.\nПриватность.","Home.\nLand.\nPrivacy.")}</p><small>{t("Для жизни и для инвестиций — с разными критериями выбора.","Different selection criteria for living and investment.")}</small></aside>}</section>
 {!data?<section className="landingSection"><div className="landingSectionHeading"><div><div className="eyebrow">{t("НАЧНИТЕ С ЦЕЛИ","START WITH YOUR GOAL")}</div><h2>{t("Что важно именно вам?","What matters to you?")}</h2></div><p>{t("Один рынок — разные задачи. Сначала определим вашу, затем выберем недвижимость.","One market, different goals. Define yours before choosing a property.")}</p></div><JourneyCards/></section>:<section className="landingSection"><div className="eyebrow">{t("КРИТЕРИИ ВЫБОРА","SELECTION CRITERIA")}</div><h2>{t("На что смотрим до покупки","What we review before purchase")}</h2><div className="criteriaGrid">{data.points.map((point,i)=><article key={point}><span>0{i+1}</span><h3>{point}</h3><p>{data.notes[i]}</p></article>)}</div></section>}
 <section className="landingMethod"><div><div className="eyebrow">{t("НЕ БРОШЮРА. ОСНОВА ДЛЯ РЕШЕНИЯ.","NOT A BROCHURE. A DECISION FRAMEWORK.")}</div><h2>{t("Красивый объект —\nтолько начало.","An attractive property\nis only the beginning.")}</h2><p>{t("Разделяем факты, прогноз девелопера и собственную оценку. Если данных недостаточно — говорим об этом прямо.","We separate facts, developer forecasts and our own estimates. When information is missing, we say so.")}</p></div><ol><li><b>{t("Проверяем исходные данные","Review the evidence")}</b><p>{t("Предложение, договор, комплектация и платежи.","Offer, contract, specifications and payments.")}</p></li><li><b>{t("Разбираем экономику и риски","Assess costs and risks")}</b><p>{t("Полная стоимость, содержание и условия выхода.","Total acquisition cost, operation and exit terms.")}</p></li><li><b>{t("Сопоставляем с вашей целью","Match your goal")}</b><p>{t("Не универсальный рейтинг, а понятные основания выбора.","Clear reasons to choose, not a one-size-fits-all rating.")}</p></li></ol></section>
 <section className="landingSection landingNext"><div><div className="eyebrow">{t("СЛЕДУЮЩИЙ ШАГ","NEXT STEP")}</div><h2>{t("От цели — к конкретному объекту.","From your goal to a property.")}</h2><p>{t("Откройте каталог и изучите полный разбор. Сценарные подборки появятся после проверки назначения каждого объекта; сейчас доступен общий каталог.","Explore the catalogue and full analysis. Goal-specific collections will follow once each property is classified; the general catalogue is available now.")}</p></div><Actions/></section>{data&&<section className="landingSection"><h2>{t("Посмотреть другие направления","Explore other directions")}</h2><JourneyCards/></section>}</main>
}
